[20.001173019] 2018-07-19 15:23:10,174 - INFO - launcher: Starting sanity checks
[21.001100540] 2018-07-19 15:23:10,175 - INFO - launcher: Checking for Python 3.5+
[21.001100540] 2018-07-19 15:23:10,175 - INFO - launcher: Checking console encoding
[21.001100540] 2018-07-19 15:23:10,175 - INFO - launcher: Setting console encoding to UTF-8
[21.001100540] 2018-07-19 15:23:10,175 - INFO - launcher: Ensuring we're in the right environment
[22.001266479] 2018-07-19 15:23:10,176 - INFO - launcher: Adding local bins/ folder to path
[23.001194000] 2018-07-19 15:23:10,177 - INFO - launcher: Required checks passed.
[23.001194000] 2018-07-19 15:23:10,177 - INFO - launcher: Optional checks passed.
[23.001194000] 2018-07-19 15:23:10,177 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.6250357627868652] 2018-07-19 15:23:10,779 - WARNING - musicbot.config | In config.py::MainThread(2632), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.6250357627868652] 2018-07-19 15:23:10,779 - INFO - musicbot.config | In config.py::MainThread(2632), line 123 in run_checks: Using i18n: config/i18n/en.json
[0.6260356903076172] 2018-07-19 15:23:10,780 - WARNING - musicbot.config | In config.py::MainThread(2632), line 293 in find_autoplaylist: No autoplaylist file found.
[0.6270358562469482] 2018-07-19 15:23:10,781 - DEBUG - musicbot.json | In json.py::MainThread(2632), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.9630551338195801] 2018-07-19 15:23:11,117 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 227 in _setup_logging: Set logging level to INFO
[0.9630551338195801] 2018-07-19 15:23:11,117 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 84 in __init__: Starting MusicBot 1.9.7
[0.9630551338195801] 2018-07-19 15:23:11,117 - WARNING - musicbot.bot | In bot.py::MainThread(2632), line 87 in __init__: Autoplaylist is empty, disabling.
[3.6532089710235596] 2018-07-19 15:23:13,808 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 232045397164425226/Lil Mocanu#9941: _play Better Now
[3.6542088985443115] 2018-07-19 15:23:13,809 - ERROR - musicbot.bot | In bot.py::MainThread(2632), line 2863 in on_message: Error in play: CommandError: The bot is not in a voice channel.  Use _summon to summon it to your voice channel.
Traceback (most recent call last):
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 2762, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 578, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use _summon to summon it to your voice channel.
[3.6572091579437256] 2018-07-19 15:23:13,812 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 1074 in on_ready: Connection established, ready to go.
[3.6572091579437256] 2018-07-19 15:23:13,812 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 339 in _cache_app_info: Caching app info
[3.8782217502593994] 2018-07-19 15:23:14,033 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 889 in _scheck_ensure_env: Ensuring data folders exist
[3.8792216777801514] 2018-07-19 15:23:14,034 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 899 in _scheck_ensure_env: Deleted old audio cache
[3.8792216777801514] 2018-07-19 15:23:14,034 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 905 in _scheck_server_permissions: Checking server permissions
[3.8802218437194824] 2018-07-19 15:23:14,035 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[3.8802218437194824] 2018-07-19 15:23:14,035 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 913 in _scheck_configs: Validating config
[3.8802218437194824] 2018-07-19 15:23:14,035 - DEBUG - musicbot.config | In config.py::MainThread(2632), line 212 in async_validate: Validating options...
[3.8802218437194824] 2018-07-19 15:23:14,035 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 916 in _scheck_configs: Validating permissions config
[3.8802218437194824] 2018-07-19 15:23:14,035 - DEBUG - musicbot.permissions | In permissions.py::MainThread(2632), line 64 in async_validate: Validating permissions...
[3.8802218437194824] 2018-07-19 15:23:14,035 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 1091 in on_ready: Connected: 469253824864059392/Mia Khalifa#3195
[3.8812220096588135] 2018-07-19 15:23:14,036 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 1099 in on_ready: Owner:     463087000312872970/Vladddh#5487

[3.8822219371795654] 2018-07-19 15:23:14,037 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 1102 in on_ready: Server List:
[3.8832221031188965] 2018-07-19 15:23:14,038 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 1105 in on_ready:  - Liverpool FC
[3.8842220306396484] 2018-07-19 15:23:14,039 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 1151 in on_ready: Not bound to any text channels
[3.8842220306396484] 2018-07-19 15:23:14,039 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 1177 in on_ready: Not autojoining any voice channels
[3.8862221240997314] 2018-07-19 15:23:14,041 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 266 in _join_startup_channels: Found resumable voice channel Liverpool FC/Camera 1
[3.8862221240997314] 2018-07-19 15:23:14,041 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 272 in _join_startup_channels: Found owner in "Camera 1"
[3.8872222900390625] 2018-07-19 15:23:14,042 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 281 in _join_startup_channels: Attempting to join Liverpool FC/Camera 1
[3.8882224559783936] 2018-07-19 15:23:14,043 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 452 in get_voice_client: Connection attempt 1 to Camera 1
[3.8882224559783936] 2018-07-19 15:23:14,043 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 391 in join_voice_channel: (join_voice_channel) creating futures
[3.8882224559783936] 2018-07-19 15:23:14,043 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 397 in join_voice_channel: (join_voice_channel) setting voice state
[3.8882224559783936] 2018-07-19 15:23:14,043 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 400 in join_voice_channel: (join_voice_channel) waiting for session id
[4.0442311763763428] 2018-07-19 15:23:14,199 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2926 in on_voice_state_update: Resumed voice connection to Liverpool FC/Camera 1
[4.0442311763763428] 2018-07-19 15:23:14,199 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2938 in on_voice_state_update: Voice state update for 469253824864059392/Mia Khalifa#3195 on Liverpool FC/Camera 1 -> [RESUME, CONNECT]
[4.0452313423156738] 2018-07-19 15:23:14,200 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 404 in join_voice_channel: (join_voice_channel) waiting for voice data
[4.2232415676116943] 2018-07-19 15:23:14,378 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 418 in join_voice_channel: (join_voice_channel) connecting...
[4.6652667522430420] 2018-07-19 15:23:14,820 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 430 in join_voice_channel: (join_voice_channel) connection successful
[4.6662669181823730] 2018-07-19 15:23:14,821 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 478 in get_voice_client: Connected in 0.8s
[4.6662669181823730] 2018-07-19 15:23:14,821 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 479 in get_voice_client: Connected to Liverpool FC/Camera 1
[4.6672668457031250] 2018-07-19 15:23:14,822 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 849 in deserialize_queue: Deserializing queue for 244517771000414209
[4.7602722644805908] 2018-07-19 15:23:14,915 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 570 in get_player: Created player via deserialization for server 244517771000414209 with 1 entries
[4.7612721920013428] 2018-07-19 15:23:14,916 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 297 in _join_startup_channels: Joined Liverpool FC/Camera 1
[4.7622723579406738] 2018-07-19 15:23:14,917 - VOICEDEBUG - musicbot.player | In player.py::MainThread(2632), line 373 in websocket_check: Starting websocket check loop for Liverpool FC
[4.7622723579406738] 2018-07-19 15:23:14,917 - DEBUG - musicbot.entry | In entry.py::MainThread(2632), line 54 in get_ready_future: Created future for None
[4.7622723579406738] 2018-07-19 15:23:14,917 - INFO - musicbot.entry | In entry.py::MainThread(2632), line 220 in _really_download: Download started: https://youtu.be/-yHoa4MR0W4?t=3
[6.4993717670440674] 2018-07-19 15:23:16,654 - INFO - musicbot.entry | In entry.py::MainThread(2632), line 230 in _really_download: Download complete: https://youtu.be/-yHoa4MR0W4?t=3
[6.5043718814849854] 2018-07-19 15:23:16,659 - FFMPEG - musicbot.player | In player.py::MainThread(2632), line 330 in _play: Creating player with options: -nostdin -vn audio_cache\youtube--yHoa4MR0W4-Post_Malone_-_Better_Now_Lyrics_Lyric_Video.webm
[6.5103721618652344] 2018-07-19 15:23:16,665 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 825 in serialize_queue: Serializing queue for 244517771000414209
[19.0860915184020996] 2018-07-19 15:23:29,240 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2938 in on_voice_state_update: Voice state update for 469253824864059392/Mia Khalifa#3195 on Liverpool FC/Camera 2 -> [JOIN, MOVE]
[19.0860915184020996] 2018-07-19 15:23:29,240 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2949 in on_voice_state_update: 469253824864059392/Mia Khalifa#3195 has joined Liverpool FC/Camera 2
[19.0870916843414307] 2018-07-19 15:23:29,241 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2964 in on_voice_state_update: Pausing in Liverpool FC/Camera 2 (joining empty channel)
[20.4681706428527832] 2018-07-19 15:23:30,623 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2938 in on_voice_state_update: Voice state update for 232045397164425226/Lil Mocanu#9941 on Liverpool FC/Camera 2 -> [JOIN, MOVE]
[20.4691705703735352] 2018-07-19 15:23:30,624 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2949 in on_voice_state_update: 232045397164425226/Lil Mocanu#9941 has joined Liverpool FC/Camera 2
[20.4691705703735352] 2018-07-19 15:23:30,624 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2977 in on_voice_state_update: Unpausing in Liverpool FC/Camera 2
[24.0853774547576904] 2018-07-19 15:23:34,240 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2938 in on_voice_state_update: Voice state update for 469253824864059392/Mia Khalifa#3195 on Liverpool FC/Camera 1 -> [JOIN, MOVE]
[24.0853774547576904] 2018-07-19 15:23:34,240 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2949 in on_voice_state_update: 469253824864059392/Mia Khalifa#3195 has joined Liverpool FC/Camera 1
[25.3664507865905762] 2018-07-19 15:23:35,521 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2938 in on_voice_state_update: Voice state update for 232045397164425226/Lil Mocanu#9941 on Liverpool FC/Camera 1 -> [JOIN, MOVE]
[25.3674509525299072] 2018-07-19 15:23:35,522 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2949 in on_voice_state_update: 232045397164425226/Lil Mocanu#9941 has joined Liverpool FC/Camera 1
[72.0381202697753906] 2018-07-19 15:24:22,192 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 463087000312872970/Vladddh#5487: _volume 0.15
[72.0421204566955566] 2018-07-19 15:24:22,196 - ERROR - musicbot.bot | In bot.py::MainThread(2632), line 2863 in on_message: Error in volume: CommandError: `0.15` is not a valid number
Traceback (most recent call last):
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 2238, in cmd_volume
    new_volume = int(new_volume)
ValueError: invalid literal for int() with base 10: '0.15'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 2841, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 2241, in cmd_volume
    raise exceptions.CommandError(self.str.get('cmd-volume-invalid', '`{0}` is not a valid number').format(new_volume), expire_in=20)
musicbot.exceptions.CommandError: `0.15` is not a valid number
[74.7442750930786133] 2018-07-19 15:24:24,899 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 463087000312872970/Vladddh#5487: _volume
[77.2584187984466553] 2018-07-19 15:24:27,413 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 463087000312872970/Vladddh#5487: _volume 15
[88.6250689029693604] 2018-07-19 15:24:38,779 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 463087000312872970/Vladddh#5487: _volume 100
[97.9866044521331787] 2018-07-19 15:24:48,141 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 463087000312872970/Vladddh#5487: _volume 25
[106.7871077060699463] 2018-07-19 15:24:56,941 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 463087000312872970/Vladddh#5487: _volume 15
[140.0140082836151123] 2018-07-19 15:25:30,168 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 232045397164425226/Lil Mocanu#9941: _volume 100
[140.0150084495544434] 2018-07-19 15:25:30,169 - ERROR - musicbot.bot | In bot.py::MainThread(2632), line 2863 in on_message: Error in volume: PermissionsError: You don't have permission to use that command.
Reason: This command is not enabled for your group (Default).
Traceback (most recent call last):
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 2816, in on_message
    expire_in=20)
musicbot.exceptions.PermissionsError: This command is not enabled for your group (Default).
[208.9499511718750000] 2018-07-19 15:26:39,104 - DEBUG - musicbot.player | In player.py::MainThread(2632), line 202 in _playback_finished: Deleting file: audio_cache\youtube--yHoa4MR0W4-Post_Malone_-_Better_Now_Lyrics_Lyric_Video.webm
[208.9519512653350830] 2018-07-19 15:26:39,106 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 825 in serialize_queue: Serializing queue for 244517771000414209
[209.1219611167907715] 2018-07-19 15:26:39,276 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2938 in on_voice_state_update: Voice state update for 232045397164425226/Lil Mocanu#9941 on Liverpool FC/Duo 1 -> [LEAVE, MOVE]
[209.1229610443115234] 2018-07-19 15:26:39,277 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2949 in on_voice_state_update: 232045397164425226/Lil Mocanu#9941 has left Liverpool FC/Camera 1
[210.7400536537170410] 2018-07-19 15:26:40,894 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(2632), line 2938 in on_voice_state_update: Voice state update for 232045397164425226/Lil Mocanu#9941 on Liverpool FC/Camera 1 -> [JOIN, MOVE]
[210.7410535812377930] 2018-07-19 15:26:40,895 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2949 in on_voice_state_update: 232045397164425226/Lil Mocanu#9941 has joined Liverpool FC/Camera 1
[258.8938076496124268] 2018-07-19 15:27:29,048 - INFO - musicbot.bot | In bot.py::MainThread(2632), line 2734 in on_message: 232045397164425226/Lil Mocanu#9941: _play https://youtu.be/kQcB8QpjfSo?list=LLJL6wjywHLfEsw9m35acnPw
[259.3588342666625977] 2018-07-19 15:27:29,513 - DEBUG - musicbot.bot | In bot.py::MainThread(2632), line 1517 in cmd_play: {'extractor_key': 'YoutubePlaylist', 'url': 'kQcB8QpjfSo', '_type': 'url', 'ie_key': 'Youtube', 'webpage_url': 'https://youtu.be/kQcB8QpjfSo?list=LLJL6wjywHLfEsw9m35acnPw', 'webpage_url_basename': 'kQcB8QpjfSo', 'extractor': 'youtube:playlist', 'id': 'kQcB8QpjfSo'}
[259.3588342666625977] 2018-07-19 15:27:29,513 - ERROR - musicbot.bot | In bot.py::MainThread(2632), line 2863 in on_message: Error in play: PermissionsError: You don't have permission to use that command.
Reason: You do not have permission to play media from this service.
Traceback (most recent call last):
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 2841, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Vlad\Desktop\MusicBot\musicbot\bot.py", line 1521, in cmd_play
    self.str.get('cmd-play-badextractor', "You do not have permission to play media from this service."), expire_in=30
musicbot.exceptions.PermissionsError: You do not have permission to play media from this service.
